### ISSUE TITLE
feat: gotouch should

### ISSUE THREAD

**Issue by baez90** [denizgursoy/gotouch#32]
**Is your feature request related to a problem? Please describe.**

When templating other Go template files (e.g. Helm templates) using the same delimiter can be annoying because you've to escape it every time like `{{ "{{" }}`. 

**Describe the solution you'd like**

It would be great to be able to change the [delimiter](https://pkg.go.dev/html/template#Template.Delims) e.g. per template in the YAML config.

**Comment by denizgursoy** [comment]
Great idea. @baez90. We will add **delimeters** to project structure and the value should be in , for example, **<< >>** format, seperated by space. But this field will not be mandatory.

**Comment by denizgursoy** [comment]
@baez90  Can you try if it works or not? I also wrote integration test to check it. Can you also inform us. Thanks for your contribution.
