### ISSUE TITLE
feat: gotouch should run without checking the suffix .yaml

### ISSUE THREAD

**Issue by rytsh** [denizgursoy/gotouch#36]
When we run with giving a yaml file, it is always checking the ".yaml" suffix even in the URL.

It should be directly run and if not unmarshal we can return error as not a yaml format.

**Comment by denizgursoy** [comment]
@rytsh validator package is doing the check. I think we can get rid of validator package to decrease binary size. But we need to writes some tests to check what validator is doing right now. If we can write a function which checks if the YAML exists and it is parsable, we can use it in gotouch main command and validate command

**Comment by baez90** [comment]
While working through my use cases I also stumbled upon this and implemented 2 custom validators:

- [yaml_url.go](https://github.com/baez90/gotouch/blob/wip/internal/validators/yaml_url.go)
- [yaml_file.go](https://github.com/baez90/gotouch/blob/wip/internal/validators/yaml_file.go)

This way it's not necessary anymore to rely on some file ending or stuff but it's parsed into a generic YAML structure and if that works, it should be valid YAML. This does not validate if the file can be parsed as project structure.

I'll create a PR probably in the upcoming days for that if you're fine with this approach?

**Comment by denizgursoy** [comment]
I am okay with that change
