### ISSUE TITLE
feat: gotouch should support auth scenarios for downloading files

### ISSUE THREAD

**Issue by baez90** [denizgursoy/gotouch#54]
## Use case

I'd like to use `gotouch` to bootstrap projects/single files in our organization but when working in an enterprise it's hardly the case that anything you're using is publicly available on the internet but rather e.g. in a protected storage like Azure DevOps artifacts.

## Possible solution

A very simple solution would be to take the [`.netrc`](https://www.gnu.org/software/inetutils/manual/html_node/The-_002enetrc-file.html) file into consideration (just like the Go CLI itself also does), parse it ( for example with [github.com/jdx/go-netrc](https://github.com/jdx/go-netrc) ) and inject credentials when downloading files and a matching entry is present.

## Alternative solution

Alternatively it would be possible to configure the credentials in the properties YAML either plain text or with a credential file similar to what [`mount.cifs`](https://linux.die.net/man/8/mount.cifs) is using

## Additional context

See also [src/cmd/go/internal/auth/auth.go](https://go.dev/src/cmd/go/internal/auth/auth.go) how Go itself is using `.netrc`.

As soon as details are settled I could also provide you with a PR if you like.

**Comment by baez90** [comment]
Looking through the code and x-checking with [go-git](/go-git/go-git) I'd be curious how you think about not only adding support for `.netrc` for HTTP downloads of packages but also adding support for SSH public key and SSH agent authentication and to also consider `.netrc` and Git credentials helpers for Git HTTP clones?

I'd be happy to provide individual PRs for:

1. introduce `.netrc` support for HTTP download of packages
1. based on 1. another PR to add `.netrc` support for Git HTTP clones
1. probably based on 1. as well another PR to support Git credential helpers?
1. based on 2. a PR to support SSH public keys (without password protection) and SSH agent authentication for Git pulls

I'll make use of most/all of the aforementioned features anyway so I'd be glad to maintain a fork for some time to see if there are some regressions/issues before you merge the PRs if you prefer 😊

**Comment by denizgursoy** [comment]
Hello, It would be great to have this features. As to `.netrc` file, is it going to work in windows machines?

**Comment by baez90** [comment]
I don't see why it wouldn't work on windows the same way as it does on Linux. Basically it is only a file in a specific format at a specific location ( `$HOME/_netrc` for Windows as it seems).

Git/cURL on Windows are using the same mechanism.

Testing of the .netrc part should be fairly easy with `httptest`. 

Testing the SSH part is a little bit more tricky but I already found a promising article about SSH client tests with a SSH server library that can be used. Although making use if the SSH agent will be fun to set up in an integration test fashion but I'll see how to do that when I get there 😄
