### ISSUE TITLE
feat: gotouch should be able to create files in the current directory

### ISSUE THREAD

**Issue by baez90** [denizgursoy/gotouch#55]
## Use case

I'd like to use `gotouch` not only to bootstrap complete projects but also to distribute common default files like:

- .gitignore
- .editorconfig
- ...

currently `gotouch` always creates a directory with the name of the module requiring the user to move the template file a level up and delete the created directory.

## Possible solutions

- introduce a flag to create files in specified directory instead of creating a new one
- introduce some kind of 'project type' and differentiate between:
    - module template
    - file template

having different kinds of project types moves the control to the properties YAML author which sounds like from an author perspective and potentially annoying from a user perspective :smile: 

Same as already mentioned in the previous issue, as soon as the details are settled I'd be happy to provide you with a PR as well!

**Comment by denizgursoy** [comment]
We can add `--inline` bool flag when gotouch is executed. For example it will look like `gotouch --inline -f path/to/file`. What do you think?

**Comment by baez90** [comment]
Yeah! Initially I thought about something longer like `--skip-module-directory-` but `--inline` is nice and short!

Do you want to implement it yourself? Otherwise I'd see to implement it beginning next week?

**Comment by denizgursoy** [comment]
You can implement it. When it is completed I can do the testing.
